{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "copilot-premium-exporter.fullname" . }}
  labels:
    {{- include "copilot-premium-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.githubToken | b64enc | quote }}
{{- end }}
