apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: copilot-premium-exporter
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/ambalbek/github_ai_usage.git
  ref:
    branch: feature
  secretRef:
    name: github-repo-creds  # remove if repo is public
